# 2023/09/19日報
## 取り組んだこと
- [プロを目指す人のためのRuby入門](https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AERuby%E5%85%A5%E9%96%80-%E6%94%B9%E8%A8%822%E7%89%88-%E8%A8%80%E8%AA%9E%E4%BB%95%E6%A7%98%E3%81%8B%E3%82%89%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA%E3%83%BB%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E6%8A%80%E6%B3%95%E3%81%BE%E3%81%A7-Software-Design/dp/4297124378/ref=sr_1_1?crid=2KR77SEG3QJJD&keywords=%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AEruby%E5%85%A5%E9%96%80&qid=1667013521&qu=eyJxc2MiOiIxLjUwIiwicXNhIjoiMS4xNiIsInFzcCI6IjEuMzUifQ%3D%3D&sprefix=%E3%83%97%E3%83%AD%E3%82%92%2Caps%2C372&sr=8-1)を読む

## わかったこと
### 例外処理のベストプラクティス
#### 安易に`rescue`を使わない
全ての例外を`rescue`すべきではない。Railsのようなフレームワークでは例外発生時の共通処理が最初から組み込まれている。  
自分で`rescue`するよりフレームワークに例外処理を委ねるほうが、不適切な実装を回避できる。  

#### `rescue`したら情報を残す
`rescue`した場合、後で原因調査できるように例外時の状況を確実に記録に残すようにする。  
最低でも発生した例外のクラス名、エラーメッセージ、バックトレースの3つはログやターミナルに出力すべき。  
これらの情報は`full_message`メソッドを使うと一度に取り出せる。  

```
# 大量のユーザにメールを送信する
users.each do |user|
  begin
    send_mail_to(user)
  rescue => e
    puts e.full_message
  end
end
```

#### 例外処理の対象範囲と対象クラスをできるだけ絞り込む
例外処理を書く場合は、例外が発生しそうな箇所と発生しそうな例外クラスをあらかじめ予想し、その予想を例外処理のコードに反映させる。  
このコードであれば、Dateオブジェクトの作成に失敗したときだけ例外が捕捉される。  
また、捕食される例外はArgmentErrorクラスに限定しているためそれ以外の例外は異常終了扱いとなる。

```
def convert_reiwa_to_date(reiwa_text)
  m = reiwa_text.match(/令和(?<jp_year>\d+)年(?<month>\d+)月(?<day>\d+)日/)
  year = m[:jp_year].to_i + 2018
  month = m[:month].to_i
  day = m[:day].to_i
  begin
    Date.new(year,mnth,day)
  rescue ArgumentError
    nil
  end
end

convert_reiwa_to_date('令和3年12月31日') #=> <Date: 2021-12-31((2459580j,0s,0n),+0s,2299161)>
convert_reiwa_to_date('令和3年99月99日') #=> nil
```

#### 例外処理よりも条件分岐を使う
例外の発生がある程度予想できる処理であれば、実際に実行する前に問題の有無を確認できる場合がある。  
Dateオブジェクトの作成でも、`Date.valid_date?`メソッドで正しい日付かどうかを確認できる。  
`begin~rescue`を使うより条件分岐を使ったほうが可読性やパフォーマンスの面で有利。  

```
require 'date'

def convert_reiwa_to_date(reiwa_text)
  m = reiwa_text.match(/令和(?<jp_year>\d+)年(?<month>\d+)月(?<day>\d+)日/)
  year = m[:jp_year].to_i + 2018
  month = m[:month].to_i
  day = m[:day].to_i
  if Date.valid_date?(year, month, day)
    Date.new(year, month, day)
  end
end

convert_reiwa_to_date('令和3年12月31日') #=> <Date: 2021-12-31((2459580j,0s,0n),+0s,2299161)>
convert_reiwa_to_date('令和3年99月99日') #=> nil
```

#### 予期しない条件は異常終了させる
`case`文で条件分岐を作る場合は、どんなパターンがやってくるか事前に分かっていることが多い。  
そういう場合は`when`節で想定可能なパターンを網羅し`else`節では「想定外のパターン」として例外を発生させる。  

```
# elseに入ったら例外を発生させる
def currency_of(country)
  case country
  when :japan
    'yen'
  when :us
    'dollar'
  when :india
    'rupee'
  else
    raise ArgumentError,"無効な国名です #{country}"
  end
end
```

#### 例外処理も手を抜かずにテストする
例外処理は「例外的状況」に対する処理。  
「例外的な状況」でしか呼び出されないため、テストしづらいケースも多いがテストがおざなりにならないようにする。  

rescue節で別の予期せぬ例外が発生すると、肝心な場面で例外処理が「例外的な状況」に対処できなくなる。  
rescue節のコードもきっちりテストを行い、正常に実行できるように検証する。  


### 例外処理についてもっと詳しく
#### `ensure`
例外処理に`ensure`節を加えることで例外が発生してもしなくても必ず実行したい処理を書くことができる。  

```
begin
  # 例外が発生するかもしれない処理
rescue
  # 例外発生時の処理
ensure
  # 例外の有無にかかわらず実行する処理
end
```

#### `ensure`の代わりにブロックを使う
ファイルの読み込みを行う場合はopenメソッドにブロックを渡すことで、ensure節やクローズ処理を書かずに済ませることができる。  
もしブロックの実行中に例外が発生した場合も、openメソッドが必ずクローズ処理を行う。

```
# ブロックつきでオープンするとメソッドの実行後に自動でクルーズ
File.open('some.txt', 'w') do |file|
  file << 'Hello'
  1/0
end
# 例外は発生するもののopenメソッドによってクローズ処理自体は必ず行われる
#=> divided by 0 (ZeroDivisionError)
```

#### 例外処理のelse
例外が発生しなかった場合に実行されるelse節を書くこともできる。  
else節はrescue節とensure節の間におく。  

```
begin
  # 例外が発生するかもしれない処理
rescue
  # 例外が発生した場合の処理
else
  # 例外が発生しなかった場合の処理
ensure
  # 例外の有無にかかわらず実行する処理
end
```

else節が使われるケースはあまり多くなく、使わなくてもbegin節に例外が発生しなかった場合の処理を書いてしまえばよい。  
ただし、begin節とは異なり、else節の中で実行されたコードはエラーが起きてもその手前に書かれたrescue節で捕捉されない。

```
begin
  puts 'Hello'
  puts '例外は発生しませんでした。'
rescue
  puts '例外は発生しました。'
# else
# puts '例外は発生しませんでした。'
end
```

#### 例外処理と戻り値
例外処理にも戻り値がある。  
例外が発生せず、最後まで正常に処理が進んだ場合はbegin節の最後の式が戻り値になる。  
また、例外が発生してその例外が捕捉された場合はrescue節の最後の式が戻り値になる。  

```
ret =
  begin
    'ok'
  rescue
    'error'
  ensure
    'ensure'
  end

ret #=> "ok"
```

```
def some_method(n)
  begin
    1 / n
    'ok'
  rescue
    'error'
  ensure
    'ensure'
  end
end

some_method(1) #=> "ok"
some_method(0) #=> "error"
```

#### `begin`/`end`を省略する`rescue`修飾子
`rescue`は修飾子として使うこともできる。  
例外が発生しなければ元の処理の値が、例外が発生した場合は`rescue`修飾子に書いた値が、それぞれ式全体の戻り値となる。  

```
# 例外が発生しない場合
1 / 1 rescue 0 #=> 1

# 例外が発生する場合
1 / 0 rescue 0 #=> 0
```

`begin`と`end`を省略できる分メソッドを短く描くことができる。  
ただし、補足する例外クラスを指定することはできない。  
`rescue`修飾子を使うとStanderdErrorとそのサブクラスが捕捉される。  

#### `$!`と`$@`に格納される例外情報
Rubyでは最後に発生した例外は組み込み変数の`$!`に格納される。  
バックトレース情報葉`$@`に格納される。  

```
begin
  1 / 0
rescue
  puts "#{$!.class}#{$!.message}"
  puts $@
end
```

#### 例外処理の`begin/end`を省略できるケース
メソッドの中身全体が例外処理で囲まれている場合は`begin`と`end`を省略することができる。  

```
def fizz_buzz(n)
  begin
    if n % 15 == 0
      'Fizz Buzz'
    elsif n % 3 == 0
      'Fizz'
    elsif n % 5 == 0
      'Buzz'
    else
      n.to_s
    end
  rescue => e
    puts "#{e.class} #{e.message}"
  end
end
```

上のコードを例外処理の`begin`と`end`を省略して次のように書く。  

```
def fizz_buzz(n)
  if n % 15 == 0
    'Fizz Buzz'
  elsif n % 3 == 0
    'Fizz'
  elsif n % 5 == 0
    'Buzz'
  else
    n.to_s
  end
  rescue => e
    puts "#{e.class} #{e.message}"
end
```

#### `rescue`した例外を再度発生させる
`rescue`節の中で`raise`メソッドを使うこともできる。  
このとき`raise`メソッドの引数を省略すると、`rescue`節で捕捉した例外をもう一度発生させることができる。  
例外が発生したらプログラム自体は異常終了させ、その情報はログに残すというとき、このテクニックが使える。  

```
def fizz_buzz(n)
  if n % 15 == 0
    'Fizz Buzz'
  elsif n % 3 == 0
    'Fizz'
  elsif n % 5 == 0
    'Buzz'
  else
    n.to_s
  end
  rescue => e
  puts "[LOG]エラーが発生しました。#{e.class} #{e.message}"
  raise
end
```

#### 独自の例外クラスを定義する
例外クラスは独自に定義することも可能。  
例外クラスを定義する場合は特別な理由がない限り、StandardErrorクラスか、そのサブクラスを継承する。  

```
clas NoCountryError < StandardError
  attr_reader :country

  def initialize(message, country)
    @country = country
    super("#{message} #{country}")
  end
end

def currency_of(country)
  case country
  when :japan
    'yen'
  when :us
    'dollar'
  when :india
    'repee'
  else
    # 独自に定義したNoCountryErrorを発生させる
    raise NoCountryError, "無効な国名です。 #{country}"
  end
end

begin
  currency_of(:italy)
rescue NoCountryError => e
  puts e.message
  puts e.country
end
#=> 無効な国名です。italy
# italy
```

## 次やること
- [プロを目指す人のためのRuby入門](https://www.amazon.co.jp/%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AERuby%E5%85%A5%E9%96%80-%E6%94%B9%E8%A8%822%E7%89%88-%E8%A8%80%E8%AA%9E%E4%BB%95%E6%A7%98%E3%81%8B%E3%82%89%E3%83%86%E3%82%B9%E3%83%88%E9%A7%86%E5%8B%95%E9%96%8B%E7%99%BA%E3%83%BB%E3%83%87%E3%83%90%E3%83%83%E3%82%B0%E6%8A%80%E6%B3%95%E3%81%BE%E3%81%A7-Software-Design/dp/4297124378/ref=sr_1_1?crid=2KR77SEG3QJJD&keywords=%E3%83%97%E3%83%AD%E3%82%92%E7%9B%AE%E6%8C%87%E3%81%99%E4%BA%BA%E3%81%AE%E3%81%9F%E3%82%81%E3%81%AEruby%E5%85%A5%E9%96%80&qid=1667013521&qu=eyJxc2MiOiIxLjUwIiwicXNhIjoiMS4xNiIsInFzcCI6IjEuMzUifQ%3D%3D&sprefix=%E3%83%97%E3%83%AD%E3%82%92%2Caps%2C372&sr=8-1)のつづき

## 感じたこと
どんな時も例外処理で対処していいわけではなく、使うところを見極めて使用しないと異常終了しないコードになってしまう。  
使いどころを見極めて不具合を隠匿しないコードを心がけたい。  

## 学習時間
- TODAY: 4h
- TOTAL: 258h
